### ISSUE TITLE
Thanks for the awesome tool!

### ISSUE THREAD

**Issue by k3yavi** [weng-lab/umitools#3]
I was wondering is there any way to access the simulated data specified in the paper?

Thanks again.

**Comment by yfu** [comment]
Hi Avi,

To get the simulation results, you can install the package and run `umi_simulator`:

```umi_simulator --cpu 8 --task amplification_rate --task-rep 10000
umi_simulator --cpu 8 --task final_pool_size --task-rep 10000
umi_simulator --cpu 8 --task pcr_cycle --task-rep 10000
umi_simulator --cpu 8 --task pcr_err --task-rep 10000
umi_simulator --cpu 8 --task pool_size --task-rep 10000
umi_simulator --cpu 8 --task sequencing_error --pool-size 10000
umi_simulator --cpu 8 --task umi_length --task-rep 10000
```
, where you can specify the number of CPU cores to use (`--cpu`), the parameter you would like to vary (`--task`), and the number of replicates (`--task-rep`). You can also check out other options by running `umi_simulator --help`.

Since this simulator was built for the purpose of testing UMIs, this script only simulates the UMI portions of reads and then outputs the PCR deduplication performance (number of reads after PCR duplicate removal using different methods) in a table.

**Comment by k3yavi** [comment]
Thanks @yfu
